### ISSUE TITLE
review completed.

### ISSUE THREAD

**Issue by hatelove** [pursuitofhappiness2017/TDDHomeworkDay2#1]
完成地相當好，production code 相當漂亮，比我之前寫得還漂亮。

commit comments 幾點摘要建議：

1. 重構的時機點可以再早一點點
1. 折扣可以用 dictionary 來取代
1. 極端的例子，可以優化 recursive 的效能，例如 第一集有一千本，其他都只有一本。後面的999次可以透過判斷只跑一次。

**Comment by pursuitofhappiness2017** [comment]
已修正並簽入, 謝謝老師的建議.
